### ISSUE TITLE
Running jake on Windows produces OSError [BUG]

### ISSUE THREAD

**Issue by benf710** [sonatype-nexus-community/jake#25]
**Description**
Running jake on Windows produces the following error:
```
> jake --help
Traceback (most recent call last):
  File "...\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\Scripts\jake.exe\__main__.py", line 4, in <module>
  File "...\lib\site-packages\jake\__main__.py", line 22, in <module>
    from os import _exit, EX_OSERR, path, mkdir
ImportError: cannot import name 'EX_OSERR' from 'os' (...\lib\os.py)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
```

**Desktop:**
 - OS: Windows 10 -    1903
 - Python: 3.6
 - Version 0.1.7

**Comment by ButterB0wl** [comment]
Merged and closed by #24 

@benf710 test out the latest release and close it out if it works on your end!

**Comment by benf710** [comment]
Tested and working on 0.2.1.
